# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-31 04:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcomment',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('OUTOFSTOCK', 'OUTOFSTOCK'), ('INSTOCK', 'INSTOCK')], default='INSTOCK', max_length=40),
        ),
    ]
