# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-31 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0002_auto_20171031_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcomment',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
